---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portalbdep-frontend
  namespace: portalbdep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portalbdep-frontend
  template:
    metadata:
      labels:
        app: portalbdep-frontend
    spec:
      containers:
      - name: frontend
        image: portal:dev
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: nginx.conf
      volumes:
        - name: nginx-config-volume
          configMap:
            name: portalbdep-nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: portalbdep-frontend-service
  namespace: portalbdep
spec:
  type: NodePort
  selector:
    app: portalbdep-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080